/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.33
 */
import {
  z as zod
} from 'zod'

/**
 * Logs in a user
 * @summary Login
 */
export const aPILoginResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().optional()
})

/**
 * Logs in a user
 * @summary Get Token
 */
export const aPIGetTokenBody = zod.object({
  "username": zod.string(),
  "password": zod.string()
})

export const aPIGetTokenResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().optional()
})

