/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.33
 */

export interface RoomSummaryOut {
  creation_time: number;
  max_participants: number;
  metadata: string;
  name: string;
  num_participants: number;
  num_publishers: number;
  sid: string;
}
