/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.33
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  User
} from '../model/user'



/**
 * Returns the current user profile
 * @summary Get Current User Profile
 */
export const aPIGetCurrentUserProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    
    return axios.get(
      `http://127.0.0.1:5002/api/users/me`,options
    );
  }


export const getAPIGetCurrentUserProfileQueryKey = () => {
    return [`http://127.0.0.1:5002/api/users/me`] as const;
    }

    
export const getAPIGetCurrentUserProfileQueryOptions = <TData = Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAPIGetCurrentUserProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>> = ({ signal }) => aPIGetCurrentUserProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData> & { queryKey: QueryKey }
}

export type APIGetCurrentUserProfileQueryResult = NonNullable<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>>
export type APIGetCurrentUserProfileQueryError = AxiosError<unknown>

/**
 * @summary Get Current User Profile
 */
export const useAPIGetCurrentUserProfile = <TData = Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof aPIGetCurrentUserProfile>>, TError, TData>>, axios?: AxiosRequestConfig}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getAPIGetCurrentUserProfileQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Deletes the current user
 * @summary Delete Current User
 */
export const aPIDeleteCurrentUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    return axios.delete(
      `http://127.0.0.1:5002/api/users/me`,options
    );
  }



export const getAPIDeleteCurrentUserMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIDeleteCurrentUser>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof aPIDeleteCurrentUser>>, TError,void, TContext> => {
 const {mutation: mutationOptions, axios: axiosOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof aPIDeleteCurrentUser>>, void> = () => {
          

          return  aPIDeleteCurrentUser(axiosOptions)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type APIDeleteCurrentUserMutationResult = NonNullable<Awaited<ReturnType<typeof aPIDeleteCurrentUser>>>
    
    export type APIDeleteCurrentUserMutationError = AxiosError<unknown>

    /**
 * @summary Delete Current User
 */
export const useAPIDeleteCurrentUser = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof aPIDeleteCurrentUser>>, TError,void, TContext>, axios?: AxiosRequestConfig}
) => {

      const mutationOptions = getAPIDeleteCurrentUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    