/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.33
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'



  export const getRoot = () => {
/**
 * @summary Root
 */
const rootRoot = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://127.0.0.1:5002/`,options
    );
  }
return {rootRoot}};
export type RootRootResult = AxiosResponse<unknown>
